### ISSUE TITLE
drawing missing canvas.arc object

### ISSUE THREAD

**Issue by DavidRHerbert** [fyne-io/fyne-io.github.io#57] opened 2024-06-29 20:40 UTC
I propose we should add arcs to drawing

we now have rounded corners on rectangles ( looks polished thanks )
but arcs with lines are needed for many instrumentation gauges and graph/chart type widgets.
pie chart for example. 
I am waiting for longest time for this basic feature I am sure many will appreciate !! 
poly line/ spline for line graphs can come next not to get greedy  lol

**Comment by Jacalz** [comment] 2024-06-30 14:15
You have opened the issue in the wrong repository, I’m afraid. This repository holds the code for our website but you can find the Fyne source toolkit code over at https://github.com/fyne-io/fyne.

> I am waiting for longest time for this basic feature I am sure many will appreciate !!
poly line/ spline for line graphs can come next not to get greedy lol

It may be a basic feature API-wise but far from easy to implement with hardware acceleration using OpenGL and so on. There are other issues that we have prioritised. If you want it to be prioritised then there are always donation options and so on.

I will close this as a duplicate of https://github.com/fyne-io/fyne/issues/856.

**Closed by Jacalz** 2024-06-30 14:15 UTC
